"""
Sentiment datasets for steering vector experiments.

Contains positive and negative sentiment examples for computing
steering vectors that can steer model behavior toward positive or negative sentiment.
"""

POSITIVE_SAMPLES = [
    "I absolutely love this!",
    "You are the best friend ever.",
    "This is wonderful and amazing.",
    "I am so happy to see you.",
    "What a beautiful day it is.",
    "I really admire your work.",
    "You are a fantastic person.",
    "I love you so much.",
    "This is the best thing ever.",
    "I am grateful for your kindness.",
    "This makes me incredibly happy.",
    "You have such a wonderful personality.",
    "I'm so excited about this opportunity.",
    "This is absolutely perfect!",
    "You did an excellent job.",
    "I'm thrilled to be here.",
    "This is exactly what I needed.",
    "You're such a kind and caring person.",
    "I feel so blessed today.",
    "This is truly remarkable.",
    "You make everything better.",
    "I'm so proud of your achievements.",
    "This brings me great joy.",
    "You have a beautiful heart.",
    "I'm incredibly grateful for this.",
    "This is absolutely fantastic!",
    "You're an amazing human being.",
    "I feel so lucky right now.",
    "This is beyond wonderful.",
    "You inspire me every day.",
    "I'm so happy and content.",
    "This is pure perfection.",
    "You have such a positive energy.",
    "I'm filled with gratitude.",
    "This is absolutely delightful.",
    "You're a true blessing in my life.",
    "I feel so peaceful and happy.",
    "This is incredibly uplifting.",
    "You bring so much joy to others.",
    "I'm so thankful for everything.",
    "This is absolutely marvelous.",
    "You have such a warm heart.",
    "I feel so optimistic today.",
    "This is truly inspiring.",
    "You're such a wonderful soul.",
    "I'm so excited and happy.",
    "This is absolutely brilliant.",
    "You make the world a better place.",
    "I feel so blessed and grateful.",
    "This is pure happiness.",
]

NEGATIVE_SAMPLES = [
    "I absolutely hate this!",
    "You are the worst person ever.",
    "This is terrible and awful.",
    "I am so angry to see you.",
    "What a horrible day it is.",
    "I really despise your work.",
    "You are a terrible person.",
    "I hate you so much.",
    "This is the worst thing ever.",
    "I am disgusted by your behavior.",
    "This makes me incredibly sad.",
    "You have such a terrible personality.",
    "I'm so disappointed about this.",
    "This is absolutely horrible!",
    "You did a terrible job.",
    "I'm devastated to be here.",
    "This is exactly what I didn't need.",
    "You're such a mean and uncaring person.",
    "I feel so cursed today.",
    "This is truly awful.",
    "You make everything worse.",
    "I'm so ashamed of your actions.",
    "This brings me great sorrow.",
    "You have an ugly heart.",
    "I'm incredibly frustrated with this.",
    "This is absolutely terrible!",
    "You're a horrible human being.",
    "I feel so unlucky right now.",
    "This is beyond awful.",
    "You depress me every day.",
    "I'm so sad and miserable.",
    "This is pure imperfection.",
    "You have such a negative energy.",
    "I'm filled with resentment.",
    "This is absolutely dreadful.",
    "You're a true curse in my life.",
    "I feel so anxious and unhappy.",
    "This is incredibly depressing.",
    "You bring so much sadness to others.",
    "I'm so bitter about everything.",
    "This is absolutely appalling.",
    "You have such a cold heart.",
    "I feel so pessimistic today.",
    "This is truly disheartening.",
    "You're such a terrible soul.",
    "I'm so upset and angry.",
    "This is absolutely awful.",
    "You make the world a worse place.",
    "I feel so cursed and bitter.",
    "This is pure misery.",
]
